version: '3'


services:

  nginx:
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - ./static:/usr/share/nginx/html/static:ro
      - ./etc/nginx.conf:/etc/nginx/nginx.conf:ro

  django:
    environment:
    - DATABASE_URL=postgres://${GATEWAY}/pbp2015
    - PGUSER
    - PGPASSWORD
    image: pbpdata:latest
    expose:
      - "8000"

#   ubuntu:
#     image: ubuntu:dpb
