# Generated by Django 2.1.5 on 2019-02-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaque', models.CharField(max_length=4)),
                ('firstname', models.CharField(max_length=22)),
                ('lastname', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=1)),
                ('country', models.CharField(max_length=2)),
                ('club', models.CharField(max_length=39)),
                ('velo', models.CharField(max_length=2)),
                ('time', models.CharField(max_length=5)),
            ],
        ),
    ]
