# Generated by Django 2.1.5 on 2019-02-11 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20190210_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timestamp',
            old_name='location',
            new_name='control',
        ),
    ]
