# Generated by Django 2.1.5 on 2019-02-09 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_control_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='control',
            old_name='outbound',
            new_name='inbound',
        ),
    ]
