# Generated by Django 2.1.5 on 2019-02-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20190209_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='seq',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
